"""Changes in payouts table

Revision ID: 35b1096a2567
Revises: 1ce38dec7306
Create Date: 2025-11-07 08:35:28.555371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b1096a2567'
down_revision = '1ce38dec7306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.drop_column('ammount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ammount', sa.FLOAT(), nullable=False))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
