"""Initial migration

Revision ID: 42e9e22fd6f7
Revises: 
Create Date: 2025-11-21 23:27:44.301572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e9e22fd6f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['bus_companies.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branches_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branches_manager_id'), ['manager_id'], unique=False)

    op.create_table('bus_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('contact_info', sa.JSON(), nullable=False),
    sa.Column('account_details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('bus_companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bus_companies_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bus_companies_status'), ['status'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_expires_at'), ['expires_at'], unique=False)

    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routes_destination'), ['destination'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_origin'), ['origin'], unique=False)
        batch_op.create_index('ix_routes_origin_destination', ['origin', 'destination'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['bus_companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('buses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('bus_number', sa.String(length=100), nullable=False),
    sa.Column('seating_capacity', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('conductor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['bus_companies.id'], ),
    sa.ForeignKeyConstraint(['conductor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buses_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buses_bus_number'), ['bus_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_buses_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buses_conductor_id'), ['conductor_id'], unique=False)

    op.create_table('employee_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('invitation_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['bus_companies.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitation_code')
    )
    with op.batch_alter_table('employee_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_invitations_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_invitations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_invitations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_invitations_status'), ['status'], unique=False)

    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('paychangu_charge_id', sa.String(length=100), nullable=True),
    sa.Column('paychangu_ref_id', sa.String(length=100), nullable=True),
    sa.Column('paychangu_status', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['bus_companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paychangu_charge_id')
    )
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payouts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payouts_paychangu_ref_id'), ['paychangu_ref_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payouts_requested_at'), ['requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payouts_status'), ['status'], unique=False)

    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_available_seats'), ['available_seats'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_bus_id'), ['bus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_departure_time'), ['departure_time'], unique=False)
        batch_op.create_index('ix_schedules_route_departure', ['route_id', 'departure_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_route_id'), ['route_id'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('seat_number', sa.String(length=20), nullable=True),
    sa.Column('qr_code_reference', sa.String(length=100), nullable=True),
    sa.Column('qr_code_reference_status', sa.String(length=20), nullable=False),
    sa.Column('payment_link', sa.String(length=200), nullable=True),
    sa.Column('tx_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('boarded_at', sa.DateTime(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_qr_code_reference'), ['qr_code_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookings_qr_code_reference_status'), ['qr_code_reference_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_schedule_id'), ['schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_seat_number'), ['seat_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_tx_ref'), ['tx_ref'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookings_user_id'), ['user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_reference'))
        batch_op.drop_index(batch_op.f('ix_transactions_payment_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_booking_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_tx_ref'))
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_seat_number'))
        batch_op.drop_index(batch_op.f('ix_bookings_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_qr_code_reference_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_qr_code_reference'))
        batch_op.drop_index(batch_op.f('ix_bookings_created_at'))

    op.drop_table('bookings')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_route_id'))
        batch_op.drop_index('ix_schedules_route_departure')
        batch_op.drop_index(batch_op.f('ix_schedules_departure_time'))
        batch_op.drop_index(batch_op.f('ix_schedules_bus_id'))
        batch_op.drop_index(batch_op.f('ix_schedules_available_seats'))

    op.drop_table('schedules')
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payouts_status'))
        batch_op.drop_index(batch_op.f('ix_payouts_requested_at'))
        batch_op.drop_index(batch_op.f('ix_payouts_paychangu_ref_id'))
        batch_op.drop_index(batch_op.f('ix_payouts_company_id'))

    op.drop_table('payouts')
    with op.batch_alter_table('employee_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_invitations_status'))
        batch_op.drop_index(batch_op.f('ix_employee_invitations_expires_at'))
        batch_op.drop_index(batch_op.f('ix_employee_invitations_email'))
        batch_op.drop_index(batch_op.f('ix_employee_invitations_company_id'))
        batch_op.drop_index(batch_op.f('ix_employee_invitations_branch_id'))

    op.drop_table('employee_invitations')
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buses_conductor_id'))
        batch_op.drop_index(batch_op.f('ix_buses_company_id'))
        batch_op.drop_index(batch_op.f('ix_buses_bus_number'))
        batch_op.drop_index(batch_op.f('ix_buses_branch_id'))

    op.drop_table('buses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_index(batch_op.f('ix_users_company_id'))
        batch_op.drop_index(batch_op.f('ix_users_branch_id'))

    op.drop_table('users')
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index('ix_routes_origin_destination')
        batch_op.drop_index(batch_op.f('ix_routes_origin'))
        batch_op.drop_index(batch_op.f('ix_routes_destination'))

    op.drop_table('routes')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_expires_at'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_email'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('bus_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bus_companies_status'))
        batch_op.drop_index(batch_op.f('ix_bus_companies_owner_id'))

    op.drop_table('bus_companies')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_manager_id'))
        batch_op.drop_index(batch_op.f('ix_branches_company_id'))

    op.drop_table('branches')
    # ### end Alembic commands ###
