"""timezone support on dates and times

Revision ID: 4955ede7e0f7
Revises: 42e9e22fd6f7
Create Date: 2025-11-22 10:23:46.946545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4955ede7e0f7'
down_revision = '42e9e22fd6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_route_departure'))
        batch_op.create_index('ix_schedules_route_departure', ['route_id', 'departure_time', 'arrival_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_arrival_time'), ['arrival_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_arrival_time'))
        batch_op.drop_index('ix_schedules_route_departure')
        batch_op.create_index(batch_op.f('ix_schedules_route_departure'), ['route_id', 'departure_time'], unique=False)

    # ### end Alembic commands ###
