"""Added payment_link column in bookings table

Revision ID: 53fd8dae492d
Revises: e5a6bffed659
Create Date: 2025-11-09 12:32:10.881899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53fd8dae492d'
down_revision = 'e5a6bffed659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_link', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('payment_link')

    # ### end Alembic commands ###
