"""Added name field in buses table

Revision ID: 6380e48f5dc8
Revises: 02e28c6b6c87
Create Date: 2025-11-17 13:43:31.163043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6380e48f5dc8'
down_revision = '02e28c6b6c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
