"""Changes in description, contact_info, and account_details field in bus_company table

Revision ID: 8d88773ad29a
Revises: f7f455e819e0
Create Date: 2025-11-04 07:59:19.727388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d88773ad29a'
down_revision = 'f7f455e819e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus_company', schema=None) as batch_op:
        batch_op.alter_column('contact_info',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('account_details',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus_company', schema=None) as batch_op:
        batch_op.alter_column('account_details',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('contact_info',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
