"""added seat_number field in bookings table

Revision ID: 8f5932145351
Revises: d4613249d985
Create Date: 2025-11-19 07:00:00.092351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5932145351'
down_revision = 'd4613249d985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seat_number', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_bookings_seat_number'), ['seat_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_seat_number'))
        batch_op.drop_column('seat_number')

    # ### end Alembic commands ###
