"""updated password length

Revision ID: b642e0cdcbed
Revises: c567685f0d7f
Create Date: 2025-11-12 02:49:30.593147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b642e0cdcbed'
down_revision = 'c567685f0d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('bookings_qr_code_reference_key'), type_='unique')

    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paychangu_charge_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('paychangu_ref_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('paychangu_status', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_payouts_paychangu_ref_id'), ['paychangu_ref_id'], unique=True)
        batch_op.create_unique_constraint(None, ['paychangu_charge_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_payouts_paychangu_ref_id'))
        batch_op.drop_column('paychangu_status')
        batch_op.drop_column('paychangu_ref_id')
        batch_op.drop_column('paychangu_charge_id')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('bookings_qr_code_reference_key'), ['qr_code_reference'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
