"""Added partner and partnership end columns to bus_companies table

Revision ID: b68b7ce51044
Revises: 4955ede7e0f7
Create Date: 2025-11-26 13:14:45.923737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68b7ce51044'
down_revision = '4955ede7e0f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus_companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('partnership_end', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_bus_companies_partner'), ['partner'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bus_companies_partner'))
        batch_op.drop_column('partnership_end')
        batch_op.drop_column('partner')

    # ### end Alembic commands ###
