"""Added employee_invitations table to track employee invitations to join a company/branch

Revision ID: d4613249d985
Revises: 6380e48f5dc8
Create Date: 2025-11-17 20:12:01.408728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4613249d985'
down_revision = '6380e48f5dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('invitation_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['bus_companies.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitation_code')
    )
    with op.batch_alter_table('employee_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_invitations_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_invitations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_invitations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_invitations_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_invitations_status'))
        batch_op.drop_index(batch_op.f('ix_employee_invitations_expires_at'))
        batch_op.drop_index(batch_op.f('ix_employee_invitations_email'))
        batch_op.drop_index(batch_op.f('ix_employee_invitations_company_id'))
        batch_op.drop_index(batch_op.f('ix_employee_invitations_branch_id'))

    op.drop_table('employee_invitations')
    # ### end Alembic commands ###
