"""Changes in the database schema

Revision ID: ef3b98b6c998
Revises: 35b1096a2567
Create Date: 2025-11-07 09:18:26.431947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3b98b6c998'
down_revision = '35b1096a2567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus_companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus_companies', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
